### ISSUE TITLE
ScriptingContainer @ApplicationScope is not a User facing API

### ISSUE THREAD

**Issue by aslakknutsen** [robertpanzer/arquillian-container-jruby#2]
The Core API Scopes are not user facing API's, but rather 'internal' extension API's. 

The idea with a @ApplicationScoped ScriptContainer is to have two separate instances between Class level and Test Method level.

If we follow how Drone does this, then the @ApplicationScoped annotation is no longer needed. The location of the injection point is what determines the scope of the ScriptContainer.

```java
@ArquillianResource
private ScriptContainer classScopedSC;

@Test
public void should(@ArquillianResource  ScriptContainer methodScopedSC) {
  
}
```

**Comment by aslakknutsen** [comment]
In hindsight.. you don't know if this is a Method or Class injection if you use the ResourceProvider.

We should add that to the SPI.

**Comment by robertpanzer** [comment]
I was just about to ask exactly that;-)
I'll take a look how drone handles this. 
Thx for the feedback! I appreciate it!

**Comment by aslakknutsen** [comment]
Drone uses the TestEnricher SPI, a level above ResourceProvider which has the separation. They have their custom @Drone annotation as well.

**Comment by robertpanzer** [comment]
Thx! I will change it this way.

**Comment by robertpanzer** [comment]
It seems that it's not possible to use @ArquillianResource with the TestEnricher because the default implementation ArquillianResourceTestEnricher will fail if it can't resolve the resource via a ResourceProvider.

I will use an own annotation like @RubyResource then.
This will also open the door to configure the injected resource via parameters.

**Comment by aslakknutsen** [comment]
Yeah, currently your only workaround would be to rely on Qualifier annotations when using Arquillian Resource. (As you are doing, just using the wrong one ;)

@ArquillianResource @RubyClassResource or @ArquillianResource @RubyMethodResource..

**Comment by aslakknutsen** [comment]
Created https://issues.jboss.org/browse/ARQ-1921

**Comment by robertpanzer** [comment]
Then I'll go with the Drone approach and completely avoid ArquillianResource.

Because your proposal of having all fields test class scoped and method params test method scoped seems perfectly logical. 
Therefore there is simply no longer a need for the scope annotations.
